/**:
  ros__parameters:
    sensors:
      names: ["Hesai_AT128", "Valeo_SCALA_L", "Valeo_SCALA_R", "ZED_X_Front",
              "ZED_Back", "OAK_D_Left", "OAK_D_Right",
              "Radar_FL", "Radar_FR", "Radar_RL", "Radar_RR"]

      Hesai_AT128:
        frame_id: "hesai_lidar"
        ns: "hesai"
        h_fov_deg: 120.0
        range: 200.0
        color: [0.0, 1.0, 0.0, 0.7]

      Valeo_SCALA_L:
        frame_id: "front_lidar_left"
        ns: "valeo_lidar"
        h_fov_deg: 133.0
        range: 150.0
        color: [0.0, 1.0, 0.0, 0.7]

      Valeo_SCALA_R:
        frame_id: "front_lidar_right"
        ns: "valeo_lidar"
        h_fov_deg: 133.0
        range: 150.0
        color: [0.0, 1.0, 0.0, 0.7]

      ZED_X_Front:
        frame_id: "zedx_base_link"
        ns: "zedx"
        h_fov_deg: 110.0
        range: 20.0
        color: [0.0, 0.9, 0.6, 0.7]

      ZED_Back:
        frame_id: "zed_back"
        ns: "zed_back"
        h_fov_deg: 110.0
        range: 20.0
        color: [0.0, 0.9, 0.6, 0.7]

      OAK_D_Left:
        frame_id: "oakd_left"
        ns: "oakd"
        h_fov_deg: 81.0
        range: 12.0
        color: [0.0, 0.9, 0.6, 0.7]

      OAK_D_Right:
        frame_id: "oakd_right"
        ns: "oakd"
        h_fov_deg: 81.0
        range: 12.0
        color: [0.0, 0.9, 0.6, 0.7]

      Radar_FL:
        frame_id: "valeo_radar_fl"
        ns: "radar"
        h_fov_deg: 140.0
        range: 200.0
        color: [0.5, 1.0, 0.0, 0.65]

      Radar_FR:
        frame_id: "valeo_radar_fr"
        ns: "radar"
        h_fov_deg: 140.0
        range: 200.0
        color: [0.5, 1.0, 0.0, 0.65]

      Radar_RL:
        frame_id: "valeo_radar_rl"
        ns: "radar"
        h_fov_deg: 140.0
        range: 200.0
        color: [0.5, 1.0, 0.0, 0.65]

      Radar_RR:
        frame_id: "valeo_radar_rr"
        ns: "radar"
        h_fov_deg: 140.0
        range: 200.0
        color: [0.5, 1.0, 0.0, 0.65]
